[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"   # Use Node 20 for functions/builds

[dev]
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["web-push", "@supabase/supabase-js"]

# Scheduled functions
[functions."cron-send-due-reminders"]
  schedule = "* * * * *"       # every minute

[functions."keepalive"]
  schedule = "0 9 * * *"       # daily at 09:00 UTC (~11:00 in Zurich now)

# Friendly /api/* routes to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
