[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"   # <- set Node here

[dev]
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["web-push", "@supabase/supabase-js"]

# Run every minute
[functions."cron-send-due-reminders"]
  schedule = "* * * * *"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."cron-keepalive"]
  schedule = "0 9 * * *"  # runs every day at 09:00 UTC
