name: Supabase Keepalive

on:
  schedule:
    - cron: '0 9 * * *'   # runs daily at 09:00 UTC (~11:00 in Zurich now)
  workflow_dispatch:       # lets you run it manually

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
    steps:
      - name: Upsert heartbeat row
        run: |
          set -e
          TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          HTTP=$(curl -sS -o out.json -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Content-Type: application/json" \
            -H "Prefer: resolution=merge-duplicates,return=representation" \
            -d "{\"id\":1,\"touched_at\":\"${TS}\"}" \
            "${SUPABASE_URL}/rest/v1/nf_heartbeat")
          echo "HTTP $HTTP"
          echo "Response:"
          cat out.json
          # Fail the job if not 2xx
          if [ "$HTTP" -lt 200 ] || [ "$HTTP" -ge 300 ]; then
            exit 1
          fi
